'use strict';const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),M=require('./model');
// Boot smoke test with a minimal document sink, not a browser or visual test.
function boot(saved){const elements=new Map();const document={getElementById:id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',addEventListener(){},setAttribute(){}});return elements.get(id);},querySelectorAll:()=>[]};const context={window:{ProjectXModel:M},document,localStorage:{getItem:()=>saved},console,Blob,URL,setTimeout};vm.runInNewContext(fs.readFileSync(__dirname+'/app.js','utf8'),context);return {app:context.window.ProjectXApp,elements};}
test('App boots with a clean PLANNER and no saved calculation',()=>{const {app,elements}=boot(null);assert.equal(app.getResult().budget,null);assert.equal(app.getState().lots.length,0);assert.equal(app.getState().sales.length,0);assert.ok(elements.get('app').innerHTML.includes('Разместить по объёму'));assert.ok(!elements.get('app').innerHTML.includes('SALE-S1'));});
test('App restores master data but always opens with a clean PLANNER',()=>{const saved=M.demo();saved.cargoTypes[0].name='SAVED CARGO';saved.sales[0].fob=77;const {app,elements}=boot(JSON.stringify(saved));assert.equal(app.getResult().budget,null);assert.equal(app.getState().lots.length,0);assert.equal(app.getState().allocations.length,0);assert.equal(app.getState().cargoTypes[0].name,'SAVED CARGO');assert.equal(app.getState().sales[0].fob,77);assert.ok(elements.get('app').innerHTML.includes('Добавьте продажи в планировщик'));assert.ok(!elements.get('app').innerHTML.includes('Проверить строки расчёта'));});
test('Corrupt or obsolete saved state falls back to blank',()=>{for(const value of ['{broken',JSON.stringify({version:1}),JSON.stringify({version:2,lots:[{},{}],ports:[{},{},{}]})])assert.equal(boot(value).app.getResult().budget,null);});

test('CARGO renders a readable three-column catalog without later-stage technical fields or cell captions',()=>{const {elements}=boot(null);elements.get('tab-cargo').onclick();const html=elements.get('app').innerHTML;assert.equal((html.match(/data-catalog-name=/g)||[]).length,97);assert.ok(html.includes('id="cargo-family"'));assert.ok(html.includes('SOLAR NPK'));assert.ok(html.includes('Planning SF, m³/t'));assert.ok(html.includes('IMSBC Group'));for(const removed of ['Hold restriction','Properties / source','Apply to parcels','UN number','Transport hazard class','SDS / declaration required','Reference estimate','N/A to this carriage mode','cargo-meta'])assert.ok(!html.includes(removed));});
test('SALE and PORTS tabs render their business registers',()=>{const {elements}=boot(null);elements.get('tab-sale').onclick();assert.ok(elements.get('app').innerHTML.includes('Реестр заключённых продаж'));assert.ok(elements.get('app').innerHTML.includes('Продаж пока нет'));elements.get('tab-ports').onclick();assert.ok(elements.get('app').innerHTML.includes('Рабочий справочник портов'));assert.ok(elements.get('app').innerHTML.includes('Ust-Luga'));});
test('Save and PDF controls belong to PLANNER and JSON export is absent',()=>{const html=fs.readFileSync(__dirname+'/index.html','utf8');assert.ok(html.includes('id="planner-actions"'));assert.ok(html.includes('id="pdf">Сохранить PDF'));assert.ok(!html.includes('Экспорт JSON'));const {elements}=boot(null);elements.get('tab-sale').onclick();assert.equal(elements.get('planner-actions').hidden,true);elements.get('tab-planner').onclick();assert.equal(elements.get('planner-actions').hidden,false);});
