'use strict';const test=require('node:test'),assert=require('node:assert/strict'),M=require('./model'),{Rational:R}=require('./arithmetic');
test('Decimal half cents round commercially, independent of binary representation',()=>{assert.equal(R.from(10.075).roundCents(),1008);assert.equal(R.from(1.005).roundCents(),101);assert.equal(R.from(100.075).roundCents(),10008);assert.equal(R.from(1).div(8).roundCents(),13);});
test('Rational operations preserve exact identities across repeating fractions',()=>{assert.equal(R.from(.1).add(.2).sub(.3).n,0n);assert.equal(R.from(1).div(3).mul(3).n,1n);assert.throws(()=>R.from(Infinity));assert.throws(()=>R.from(1).div(0));});
test('A half-cent miscellaneous cost is not rounded down',()=>{const s=M.demo();s.costs=[{name:'fee',amount:10.075,days:0,burn:0,fuel:'main'}];assert.equal(M.compute(s).budget.rows.find(r=>r.name==='fee').cents,1008);});
test('Other income is rounded to cents consistently in net and P&L',()=>{const s=M.demo(),base=M.compute(s).budget;s.extraIncome=1.005;const b=M.compute(s).budget;assert.equal(Math.round((b.net-base.net)*100),101);assert.equal(Math.round((b.pnl-base.pnl)*100),101);});
test('Overflow cannot silently remove a cost line',()=>{const s=M.demo();s.costs=[{name:'huge',amount:1e20,days:0,burn:0,fuel:'main'}];assert.equal(M.compute(s).budget,null);});
test('Overflow in freight income blocks result even if voyage costs fit',()=>{const s=M.demo();s.freight=1e20;assert.equal(M.compute(s).budget,null);});
test('PDA and handling assumptions survive deselect/reselect of load parcel',()=>{const s=M.demo();s.lots[1].loadPort='Murmansk';M.syncRoute(s);const p=s.ports.find(p=>p.name==='Murmansk');p.da=98765;p.rate=1234;s.lots[1].selected=false;M.syncRoute(s);s.lots[1].selected=true;M.syncRoute(s);assert.equal(s.ports.find(p=>p.name==='Murmansk').da,98765);assert.equal(s.ports.find(p=>p.name==='Murmansk').rate,1234);});
test('Snapshot mismatch and duplicate parcel IDs cannot produce financial result',()=>{for(const mutate of [s=>s.vesselId='nonexistent',s=>s.lots[1].id=s.lots[0].id]){const s=M.demo();mutate(s);assert.equal(M.compute(s).budget,null);}});
test('Largest remainder allocation is exact with decimal weights and large amounts',()=>{for(const weights of [[.1,.2,.3],[1.001,.002,4000.9],[.00001,12345.6]]){const a=M.splitCents(99999999999,weights);assert.equal(a.reduce((x,y)=>x+y,0),99999999999);assert.ok(a.every(Number.isSafeInteger));}assert.throws(()=>M.splitCents(1,[-1,2]));});
test('Displayed two-decimal covering freight actually covers rounded costs and commission',()=>{const s=M.demo();s.commission=3.75;s.extraIncome=1.005;const b=M.compute(s).budget;s.freight=b.requiredFreightQuote;const actual=M.compute(s).budget;assert.ok(actual.pnl>=0);assert.equal(R.from(s.freight).mul(100).d,1n);});
test('Optional ECA burn must be finite and nonnegative when set in catalog',()=>{const s=M.initial();s.vesselProfiles[0].ecaBurn=-1;assert.throws(()=>M.applyVessel(s,'tbn-1'));});
test('Covering quote remains sufficient for tiny quantities and rounded commission',()=>{const s=M.demo();s.lots[0].quantity=.00001;s.lots[1].selected=false;s.commission=33.333;s.freight=null;const b=M.compute(s).budget;assert.ok(b);s.freight=b.requiredFreightQuote;assert.ok(M.compute(s).budget.pnl>=0);});
test('Zero boiler burn does not require boiler operating days',()=>{const s=M.demo();s.ports[0].boiler=0;s.ports[0].boilerDays=null;assert.ok(M.compute(s).budget);});
test('Missing SF is an explicit stowage error while financial scope stays separate',()=>{const s=M.demo();s.lots[0].sf=null;const r=M.compute(s);assert.ok(r.budget);assert.ok(r.ship.errors.some(x=>x.includes('SF')));assert.equal(r.ship.holds[0].used,null);});
test('Deleted deduction cannot silently overstate intake',()=>{const s=M.demo();delete s.deductions.water;assert.equal(M.stowage(s).intake,null);assert.ok(M.stowage(s).warnings.some(x=>x.includes('DWT limit is unknown')));});
test('Duplicate hold identity and invalid assigned quantity are detected',()=>{const s=M.demo();s.holds[1].id=s.holds[0].id;assert.ok(M.stowage(s).errors.includes('Duplicate hold ID'));s.allocations[0].quantity=null;assert.equal(M.stowage(s).holds[0].used,null);assert.equal(M.stowage(s).holds[0].quantity,null);});
test('A mixed loading/discharge call cannot publish an ambiguous plan budget',()=>{const s=M.demo();s.lots[1].loadPort='Santos';M.syncRoute(s);const r=M.compute(s);assert.equal(r.budget,null);assert.ok(r.errors.some(x=>x.includes('operation sequence')));});
test('Boiler days without consumption and negative days cannot be ignored',()=>{for(const fields of [{boiler:null,boilerDays:1},{boiler:0,boilerDays:-1}]){const s=M.demo();Object.assign(s.ports[0],fields);assert.equal(M.compute(s).budget,null);}});
test('Exact decimal calendar equality is accepted and a shorter one is rejected',()=>{const s=M.demo();s.lots[0].quantity=1;s.lots[1].selected=false;Object.assign(s.ports[0],{rate:10,terms:'manual',calendar:.1});assert.ok(M.compute(s).budget);s.ports[0].calendar=.09999999999999999;assert.equal(M.compute(s).budget,null);});
test('Every cost line has a trace matching the rounded amount and allocation evidence',()=>{const s=M.demo();s.costs=[{name:'Stop',amount:10.075,days:.3,burn:.7,fuel:'main'}];const b=M.compute(s).budget;const lines=[...b.trace.legs,...b.trace.ports,...b.trace.extras];for(const row of b.rows){const entry=lines.find(x=>x.label===row.name);assert.ok(entry,row.name);assert.equal(entry.result,row.cents/100);assert.ok(entry.formula&&entry.substitution);for(const [id,share]of Object.entries(row.shares)){const exact=R.from(row.cents).mul(row.weights[id]).div(row.basis);assert.equal(share,Number(exact.n/exact.d)+row.rounding[id]);assert.ok([0,1].includes(row.rounding[id]));}}for(const e of Object.values(b.trace).flat())assert.ok(Number.isFinite(e.result));assert.ok(b.trace.totals.some(e=>e.label==='TCE before hire'&&e.result===b.tce));});
test('Unknown financial inputs publish neither a budget nor fabricated numeric evidence',()=>{const s=M.demo();s.prices.main=null;const r=M.compute(s);assert.equal(r.budget,null);assert.equal(r.trace,undefined);});
test('Freight and other income cancellation remain exact near the monetary range',()=>{const s=M.demo();s.lots[0].quantity=1;s.lots[1].selected=false;s.freight=90071992547409.9;s.commission=50;s.extraIncome=45035996273704.94;const b=M.compute(s).budget;assert.ok(b);assert.equal(b.net,90071992547409.89);});
test('Allocation follows reordered discharge and ballast remains shared',()=>{const s=M.demo();M.moveCall(s,'Paranaguá',-1);s.legs.forEach(l=>Object.assign(l,{distance:240,eca:0,speed:10,margin:0,burn:1,ecaBurn:0,aux:0}));Object.assign(s.ballast,{distance:240,eca:0,speed:10,margin:0,burn:1,ecaBurn:0,aux:0});s.ballastEnabled=true;const b=M.compute(s).budget;assert.ok(b);const onward=b.rows.find(x=>x.name==='Paranaguá → Santos · hire');assert.equal(onward.shares.S2,0);assert.equal(onward.shares.S1,onward.cents);const ballast=b.rows.find(x=>x.name.startsWith('Vessel position')&&x.kind==='hire');assert.ok(ballast.shares.S1>0&&ballast.shares.S2>0);});
test('The integer fast path in Rational.from is the same number as the decimal parse',()=>{
 // Values that must reduce to the identical numerator/denominator, fast path or not.
 const decimal=v=>{const [mantissa,exp='0']=String(v).toLowerCase().split('e');const negative=mantissa.startsWith('-');
  const parts=mantissa.replace('-','').split('.');const power=Number(exp)-(parts[1]?.length||0);
  let n=BigInt(parts.join(''));if(negative)n=-n;
  return power>=0?R.from(n*10n**BigInt(power)):new (Object.getPrototypeOf(R.from(1)).constructor)(n,10n**BigInt(-power));};
 const values=[0,-0,1,-1,7,-7,1000,33465,-56565,9007199254740991,-9007199254740991,1e21,-1e21,2**53,0.1,-0.1,1.005,10.075,0.970873786407767,-0.000123,12345678901234.5];
 for(const v of values){const a=R.from(v),b=decimal(v);
  assert.equal(a.n,b.n,'numerator for '+v);assert.equal(a.d,b.d,'denominator for '+v);}
 // and the arithmetic identities still hold
 assert.equal(R.from(.1).add(.2).sub(.3).n,0n);
 assert.equal(R.from(30000).sub(24000).number(),6000);
 assert.equal(R.from(9007199254740991).add(1).number(),9007199254740992);
 assert.throws(()=>R.from(Infinity));assert.throws(()=>R.from(NaN));
});
