(function(root){
'use strict';
const CargoCatalog=typeof module!=='undefined'&&module.exports?require('./cargo-catalog'):root.ProjectXCargoCatalog;
function isBulkCargo(c){return !c?.physicalForm||c.physicalForm==='solid';}

const ok=(x,p=false)=>typeof x==='number'&&Number.isFinite(x)&&(p?x>0:x>=0);
const {Rational}=typeof module!=='undefined'&&module.exports?require('./arithmetic'):root.ProjectXArithmetic;
const sum=a=>a.reduce((n,x)=>n+x,0),R=x=>Rational.from(x),cents=x=>R(x).roundCents();
// Invalid fields are validated by need(); these placeholders never produce a published budget.
const rInput=x=>typeof x==='number'&&Number.isFinite(x)?R(x):R(0);
const ratio=(a,b)=>b.n===0n?R(0):a.div(b);
const rsum=xs=>xs.reduce((n,x)=>n.add(x),R(0));
const port=name=>({name,rate:null,terms:'SHINC',calendar:null,turn:0,extra:0,da:null,working:4.8,idle:2.7,aux:null,fuel:'eca'});
const leg=(from,to)=>({from,to,distance:null,eca:null,speed:12.5,burn:16,ecaBurn:null,aux:null,margin:0});
const VESSELS=[{"id":"tbn-1","name":"TBN 1 · 33K","direction":"Россия → Бразилия","dwt":33466,"draft":9.85,"tpc":50.7,"loa":180,"beam":30,"grain":45517,"bale":45517,"holds":5,"model":"Стандартный балкер","source":"Стандартный профиль TBN 1","revision":"standard-tbn1-v1","gt":24079,"nrt":10640,"lbp":176.75,"depth":14.7,"lightship":10255.5,"constant":250,"tanktop":22,"grabs":false,"speed":10.2,"burn":17,"ballastSpeed":10.7,"ballastBurn":17,"working":0,"idle":0,"aux":2,"auxWorking":3.5,"auxIdle":3,"boiler":1,"ecaBurn":null,"cranes":4,"craneSWL":30,"holdData":[{"id":1,"volume":7781.4,"massLimit":null,"baleMin":7003.2,"baleMax":7781.4},{"id":2,"volume":9489.1,"massLimit":null,"baleMin":9014.7,"baleMax":9489.1},{"id":3,"volume":9484.5,"massLimit":null,"baleMin":9010.3,"baleMax":9484.5},{"id":4,"volume":9487.6,"massLimit":null,"baleMin":9013.22,"baleMax":9487.6},{"id":5,"volume":9274.3,"massLimit":null,"baleMin":8346.9,"baleMax":9274.3}]}];
const vesselOf=s=>(s.vesselSnapshot?.id===s.vesselId?s.vesselSnapshot:null)||VESSELS.find(v=>v.id===(s.vesselId||'tbn-1'));
const LOAD_PORTS=['Ust-Luga','Murmansk','St. Petersburg'];
const loadOf=(s,l)=>l.loadPort??s.ports[0].name;
const callsOf=s=>s.ports.filter(p=>active(s).some(l=>loadOf(s,l)===p.name||l.port===p.name));
const CARGO_TYPES=[{name:'BULK SULPHUR APP C',group:''},{name:'CRUSHED LUMP SULPHUR',group:'B',un:'1350',onlyHold:4}];
function initial(){const s={version:2,vesselId:'tbn-1',cargoTypes:JSON.parse(JSON.stringify(CARGO_TYPES)),sales:[],portRecords:[{id:'P1',name:'Ust-Luga',terminal:'',restrictions:'',da:null},{id:'P2',name:'Santos',terminal:'',restrictions:'',da:null},{id:'P3',name:'Paranaguá',terminal:'',restrictions:'',da:null}],demo:false,notes:'',lots:[],holds:JSON.parse(JSON.stringify(VESSELS[0].holdData)),allocations:[],stage:'load',deductions:{fuel:null,water:null,ballast:null,constant:null,lubes:null,slops:null},ports:[port('Ust-Luga'),port('Santos'),port('Paranaguá')],legs:[leg('Ust-Luga','Santos'),leg('Santos','Paranaguá')],ballastEnabled:false,ballast:leg('Позиция судна','Ust-Luga'),prices:{main:null,eca:null,aux:null},hire:null,commission:0,freight:null,extraIncome:0,costs:[],allocation:'route'};ensureCatalogs(s);ensureBusinessData(s);applyVessel(s,'tbn-1');s.deductions.constant=250;s.tbnSourceRevision=VESSELS[0].revision;return s;}
function demo(){const s=initial();s.lots=[{id:'S1',name:'BULK SULPHUR APP C',cargoId:'cargo-1',saleId:'SALE-S1',color:'#d5ae60',selected:true,quantity:24000,sf:.9,loadPort:'Ust-Luga',port:'Santos'},{id:'S2',name:'CRUSHED LUMP SULPHUR',cargoId:'cargo-2',saleId:'SALE-S2',color:'#829fcb',selected:true,quantity:6000,sf:.9,loadPort:'Ust-Luga',port:'Paranaguá',onlyHold:4,group:'B',un:'1350'}];s.sales=[{id:'SALE-S1',dealDate:'',cargoId:'cargo-1',cargoName:'BULK SULPHUR APP C',quantity:24000,loadPort:'Ust-Luga',dischargePort:'Santos',shipmentFrom:'',shipmentTo:'',fob:null},{id:'SALE-S2',dealDate:'',cargoId:'cargo-2',cargoName:'CRUSHED LUMP SULPHUR',quantity:6000,loadPort:'Ust-Luga',dischargePort:'Paranaguá',shipmentFrom:'',shipmentTo:'',fob:null}];s.vesselSnapshot={...s.vesselSnapshot,dwt:37667};s.holds=[7948,9790,9782,9782,9428].map((volume,i)=>({id:i+1,volume,massLimit:null}));s.ports=[port('Ust-Luga'),port('Santos'),port('Paranaguá')];s.legs=[leg('Ust-Luga','Santos'),leg('Santos','Paranaguá')];s.ports.forEach(p=>{delete p.auxWorking;delete p.auxIdle;delete p.boiler;delete p.boilerDays;delete p.boilerFuel;p.working=4.8;p.idle=2.7;});s.demo=true;s.deductions={fuel:950,water:200,ballast:300,constant:450,lubes:35,slops:40};s.hire=13500;s.freight=50;s.commission=1.25;s.prices={main:540,eca:800,aux:800};s.ports.forEach((p,i)=>Object.assign(p,{rate:i?5000:8000,da:[65000,55000,42000][i],aux:0,fuel:i?'main':'eca'}));s.legs.forEach((l,i)=>Object.assign(l,{distance:i?180:7200,speed:12.5,burn:16,eca:i?0:1000,ecaBurn:16,aux:0,margin:5}));s.allocations=allocate(s);return s;}
function active(s){return s.lots.filter(l=>l.selected);}
function allocate(s){const out=[];const lots=active(s).filter(l=>isBulkCargo(s.cargoTypes?.find(c=>c.id===l.cargoId))&&ok(l.quantity,true)&&ok(l.sf,true)).sort((a,b)=>(!!b.onlyHold-!!a.onlyHold));for(const l of lots){let left=l.quantity;for(const h of s.holds){if(l.onlyHold&&h.id!==l.onlyHold||!l.onlyHold&&lots.some(x=>x.onlyHold===h.id)||out.some(a=>a.hold===h.id))continue;const q=Math.min(left,h.volume/l.sf,h.massLimit??Infinity);if(ok(q,true)){out.push({lot:l.id,hold:h.id,quantity:q});left-=q;}if(left<1e-9)break;}}return out;}
function stowage(s){const lots=active(s),errors=[],warnings=[];const intake=Object.values(s.deductions).every(x=>ok(x))?(vesselOf(s)?.dwt??NaN)-sum(Object.values(s.deductions)):null;const quantity=lots.every(l=>ok(l.quantity,true))?sum(lots.map(l=>l.quantity)):null;
for(const l of lots){if(['reference-upper-bound','SDS-loose-density'].includes(l.sfBasis))warnings.push(l.id+': SF — справочная оценка; подтвердите значение партии');if(!isBulkCargo(s.cargoTypes?.find(c=>c.id===l.cargoId)))errors.push(l.name+': форма перевозки не поддерживается балкером');}
for(const a of s.allocations){const l=lots.find(l=>l.id===a.lot);if(!l||!s.holds.some(h=>h.id===a.hold)||!ok(a.quantity))errors.push('Некорректная запись размещения');else if(l.onlyHold&&a.hold!==l.onlyHold&&a.quantity>0)errors.push(l.name+': разрешён только трюм №'+l.onlyHold);}
const holds=s.holds.map(h=>{const all=s.allocations.filter(a=>a.hold===h.id&&lots.some(l=>l.id===a.lot));const q=sum(all.map(a=>a.quantity));const volume=all.every(a=>ok(lots.find(l=>l.id===a.lot).sf,true))?sum(all.map(a=>a.quantity*lots.find(l=>l.id===a.lot).sf)):null;if(!ok(h.volume,true))errors.push('Укажите объём трюма №'+h.id);if(h.massLimit!==null&&!ok(h.massLimit,true))errors.push('Проверьте предел массы №'+h.id);if(volume!==null&&volume>h.volume+1e-7)errors.push('Превышен объём трюма №'+h.id);if(h.massLimit!==null&&q>h.massLimit+1e-7)errors.push('Превышена масса трюма №'+h.id);if(new Set(all.filter(a=>a.quantity>0).map(a=>a.lot)).size>1)warnings.push('Совместное размещение в №'+h.id+' требует проверки совместимости');return {...h,quantity:q,used:volume,fill:volume===null?null:100*volume/h.volume};});
const remaining=lots.map(l=>{const q=sum(s.allocations.filter(a=>a.lot===l.id).map(a=>a.quantity));if(ok(l.quantity)&&q>l.quantity+1e-7)errors.push(l.id+': размещено больше партии');return {id:l.id,quantity:ok(l.quantity)?l.quantity-q:null};});if(intake!==null&&quantity!==null&&quantity>intake)errors.push('Суммарная масса превышает DWT минус вычеты');if(intake!==null&&intake<0)errors.push('Вычеты превышают DWT');return {intake,quantity,holds,remaining,errors:[...new Set(errors)],warnings};}
function splitCents(total,weights){if(!Number.isSafeInteger(total)||total<0||weights.some(w=>!ok(w)))throw Error('Некорректная база распределения');const denominator=rsum(weights.map(R));if(denominator.n===0n)throw Error('Нет базы распределения');const shares=weights.map(w=>R(total).mul(w).div(denominator));const out=shares.map(x=>Number(x.n/x.d));const order=shares.map((x,i)=>({i,n:x.n%x.d,d:x.d})).sort((a,b)=>{const difference=b.n*a.d-a.n*b.d;return difference>0n?1:difference<0n?-1:a.i-b.i;});const remainder=total-sum(out);for(let i=0;i<remainder;i++)out[order[i].i]++;return out;}
function compute(s){try{return computeChecked(s);}catch(error){return {errors:['Расчёт остановлен: '+error.message],ship:stowage(s),budget:null};}}
function computeChecked(s){const errors=[],lots=active(s),ship=stowage(s);if(new Set(s.lots.map(l=>l.id)).size!==s.lots.length)errors.push('Повторяющиеся ID партий');if(s.vesselSnapshot&&s.vesselSnapshot.id!==s.vesselId)errors.push('Профиль судна не соответствует выбранному типу');const need=(x,label,p=false)=>{if(!ok(x,p))errors.push(label);};if(!vesselOf(s))errors.push('Выберите судно');if(!lots.length)errors.push('Выберите партию');for(const l of lots){need(l.quantity,l.id+': тоннаж',true);if(!['Santos','Paranaguá'].includes(l.port))errors.push(l.id+': порт');if(!LOAD_PORTS.includes(loadOf(s,l)))errors.push(l.id+': порт погрузки');}need(s.hire,'Ставка найма');need(s.commission,'Комиссия');if(s.commission>=100)errors.push('Комиссия должна быть меньше 100%');need(s.extraIncome,'Дополнительный доход');if(s.freight!==null)need(s.freight,'Ставка фрахта');
const names=s.ports.map(p=>p.name);if(new Set(names).size!==names.length||!names.includes('Santos')||!names.includes('Paranaguá'))errors.push('Проверьте маршрут');for(const l of lots){if(!names.includes(loadOf(s,l))||names.indexOf(loadOf(s,l))>=names.indexOf(l.port))errors.push(l.id+': погрузка должна предшествовать выгрузке');}if(!['route','tonnage'].includes(s.allocation))errors.push('Метод распределения');
const q=sum(lots.map(l=>ok(l.quantity)?l.quantity:0));const calls=callsOf(s);const legs=[];for(let i=1;i<calls.length;i++){const x=s.legs.find(l=>l.from===calls[i-1].name&&l.to===calls[i].name);if(!x)errors.push('Расстояние '+calls[i-1].name+' → '+calls[i].name+': перестройте маршрут');else legs.push(x);}if(s.ballastEnabled){if(s.ballast.to!==calls[0]?.name)errors.push('Балластный подход должен завершаться в первом порту');legs.unshift(s.ballast);}
let sea=0,work=0,idle=0,totalDaysR=R(0);const usage={main:0,eca:0,aux:0},rows=[],legResults=[],portResults=[];
const add=(name,amount,eligible,kind)=>{const value=cents(amount);if(value<0)errors.push(name+': отрицательная стоимость');rows.push({name,cents:value,eligible:eligible.map(l=>l.id),kind});};
const fuelCost=(fuel,mass)=>{mass=R(mass);if(mass.n===0n)return R(0);need(s.prices[fuel],'Цена топлива '+fuel);usage[fuel]+=mass.number();return mass.mul(rInput(s.prices[fuel]));};
for(const l of legs){const label=l.from+' → '+l.to;for(const [k,p]of [['distance',true],['speed',true],['burn',false],['eca',false],['margin',false],['aux',false]])need(l[k],label+': '+k,p);if(l.eca>l.distance)errors.push(label+': ECA больше полного расстояния');if(l.eca>0)need(l.ecaBurn,label+': расход ECA');const factor=rInput(l.margin).div(100).add(1),daysR=ratio(rInput(l.distance),rInput(l.speed).mul(24)).mul(factor),ecaR=ratio(rInput(l.eca),rInput(l.speed).mul(24)).mul(factor),days=daysR.number(),ecaDays=ecaR.number();totalDaysR=totalDaysR.add(daysR);const before=s.ports.findIndex(p=>p.name===l.from);const eligible=l===s.ballast?lots:lots.filter(x=>s.ports.findIndex(p=>p.name===loadOf(s,x))<=before&&s.ports.findIndex(p=>p.name===x.port)>before);const mainR=daysR.sub(ecaR).mul(rInput(l.burn)),ecaMassR=ecaR.mul(rInput(l.ecaBurn)),auxR=daysR.mul(rInput(l.aux)),massMain=mainR.number(),massEca=ecaMassR.number(),massAux=auxR.number();const costR=fuelCost('main',mainR).add(fuelCost('eca',ecaMassR)).add(fuelCost('aux',auxR)),cost=costR.number();sea+=days;add(label+' · топливо',costR,eligible,'fuel');add(label+' · найм',daysR.mul(rInput(s.hire)),eligible,'hire');legResults.push({...l,days,ecaDays,massMain,massEca,massAux,cost});}
for(const p of calls){const eligible=lots.filter(l=>loadOf(s,l)===p.name||l.port===p.name);const cargo=sum(eligible.map(l=>l.quantity));need(p.rate,p.name+': норма',true);for(const k of ['turn','extra','da','working','idle'])need(p[k],p.name+': '+k);const auxWorking=p.auxWorking===undefined?p.aux:p.auxWorking,auxIdle=p.auxIdle===undefined?p.aux:p.auxIdle;need(auxWorking,p.name+': Aux working');need(auxIdle,p.name+': Aux idle');if(!['main','eca'].includes(p.fuel))errors.push(p.name+': топливо');if(!['SHINC','manual'].includes(p.terms))errors.push(p.name+': условия обработки');const workR=ratio(rsum(eligible.map(l=>rInput(l.quantity))),rInput(p.rate)),workDays=workR.number();let calendar=workDays;if(p.terms==='manual'){need(p.calendar,p.name+': календарные дни обработки',true);calendar=p.calendar;if(calendar<workDays)errors.push(p.name+': календарный период меньше рабочих дней');}const calendarR=p.terms==='manual'?rInput(p.calendar):workR,idleR=rInput(p.turn).add(rInput(p.extra)).div(24).add(calendarR).sub(workR),daysR=workR.add(idleR),idleDays=idleR.number(),days=daysR.number();totalDaysR=totalDaysR.add(daysR);let boilerCost=R(0);if(p.boiler!==undefined){need(p.boiler,p.name+': котёл т/сут');if(p.boiler!==0)need(p.boilerDays,p.name+': работа котла, суток');if(p.boilerDays>days)errors.push(p.name+': работа котла больше времени в порту');if(p.boilerDays>0&&p.boiler>0){if(!['main','eca','aux'].includes(p.boilerFuel))errors.push(p.name+': топливо котла');else boilerCost=fuelCost(p.boilerFuel,rInput(p.boilerDays).mul(rInput(p.boiler)));}}const costR=fuelCost(p.fuel,workR.mul(rInput(p.working)).add(idleR.mul(rInput(p.idle)))).add(fuelCost('aux',workR.mul(rInput(auxWorking)).add(idleR.mul(rInput(auxIdle))))).add(boilerCost),cost=costR.number();work+=workDays;idle+=idleDays;add(p.name+' · DA',rInput(p.da),eligible,'ports');add(p.name+' · топливо',costR,eligible,'fuel');add(p.name+' · найм',daysR.mul(rInput(s.hire)),eligible,'hire');portResults.push({...p,cargo,workDays,idleDays,days,cost});}
for(const c of s.costs){need(c.amount,c.name+': сумма');need(c.days,c.name+': дни');need(c.burn,c.name+': расход');if(!['main','eca'].includes(c.fuel))errors.push(c.name+': топливо');add(c.name,rInput(c.amount),lots,'other');const cost=fuelCost(c.fuel,rInput(c.days).mul(rInput(c.burn)));add(c.name+' · топливо',cost,lots,'fuel');add(c.name+' · найм',rInput(c.days).mul(rInput(s.hire)),lots,'hire');idle+=c.days;totalDaysR=totalDaysR.add(rInput(c.days));}
const days=totalDaysR.number();if(!ok(days,true))errors.push('Продолжительность рейса');if(errors.length)return {errors:[...new Set(errors)],ship,budget:null};
const totalCents=sum(rows.map(r=>r.cents));if(!Number.isSafeInteger(totalCents))return {errors:['Сумма вне точного денежного диапазона'],ship,budget:null};const allocation=lots.map(l=>({id:l.id,cents:0,quantity:l.quantity}));for(const row of rows){const weights=lots.map(l=>(s.allocation==='tonnage'||row.eligible.includes(l.id))?l.quantity:0);const portions=splitCents(row.cents,weights);portions.forEach((x,i)=>allocation[i].cents+=x);row.shares=Object.fromEntries(lots.map((l,i)=>[l.id,portions[i]]));}
const total=totalCents/100,hire=sum(rows.filter(r=>r.kind==='hire').map(r=>r.cents))/100,voyage=total-hire,quantityR=rsum(lots.map(l=>R(l.quantity))),grossCents=s.freight===null?null:cents(quantityR.mul(s.freight)),commissionCents=grossCents===null?null:cents(R(grossCents).div(100).mul(s.commission).div(100)),extraCents=cents(s.extraIncome),netCents=grossCents===null?null:grossCents-commissionCents+extraCents,gross=grossCents===null?null:grossCents/100,commission=commissionCents===null?null:commissionCents/100,net=netCents===null?null:netCents/100;
if(netCents!==null&&!Number.isSafeInteger(netCents))throw RangeError('Доход вне точного денежного диапазона');
const neededNetCents=Math.max(0,totalCents-extraCents),grossNeeded=R(neededNetCents).div(R(1).sub(R(s.commission).div(100))),grossNeededCents=(grossNeeded.n+grossNeeded.d-1n)/grossNeeded.d;const rateUnits=R(grossNeededCents).div(quantityR),quoteUnits=(rateUnits.n+rateUnits.d-1n)/rateUnits.d,requiredFreightQuote=R(quoteUnits).div(100).number();
return {errors:[],ship,budget:{q,days,sea,work,idle,usage,rows,legs:legResults,ports:portResults,totalCents,total,hire,voyage,requiredFreightQuote,unit:total/q,requiredFreight:Math.max(0,R(totalCents-extraCents).div(100).div(quantityR.mul(R(1).sub(R(s.commission).div(100)))).number()),gross,commission,net,tce:net===null?null:(net-voyage)/days,pnl:netCents===null?null:(netCents-totalCents)/100,allocation}};}
function stageAllocations(s){if(s.stage==='load')return s.allocations;const index=s.ports.findIndex(p=>p.name===s.stage);return s.allocations.filter(a=>{const l=s.lots.find(l=>l.id===a.lot);return l&&s.ports.findIndex(p=>p.name===loadOf(s,l))<=index&&s.ports.findIndex(p=>p.name===l.port)>index;});}
function changeLoadPort(s,name,code=''){if(!name.trim()||s.ports.slice(1).some(p=>p.name===name))throw Error('Выберите порт погрузки, отличный от выгрузки');const old=s.ports[0].name;if(old===name&&s.ports[0].code===code)return;s.lots.forEach(l=>l.loadPort=name);s.ports[0]={...port(name),code};s.legs=s.legs.filter(l=>l.from!==old&&l.to!==old);s.ballast=leg('Позиция судна',name);s.stage='load';}
function addLot(s,data){if(!data.name?.trim())throw Error('Введите вид груза');if(!ok(data.quantity,true)||!ok(data.sf,true))throw Error('Укажите положительные тоннаж и SF');if(!['Santos','Paranaguá'].includes(data.port))throw Error('Выберите порт выгрузки');if(data.loadPort&&!LOAD_PORTS.includes(data.loadPort))throw Error('Выберите порт погрузки');const ids=new Set(s.lots.map(l=>l.id));let n=1;while(ids.has('S'+n))n++;s.cargoTypes??=JSON.parse(JSON.stringify(CARGO_TYPES));const known=s.cargoTypes.find(l=>l.name.toLowerCase()===data.name.trim().toLowerCase());if(known&&!isBulkCargo(known))throw Error('Этот продукт требует другой формы перевозки и недоступен для трюмов балкера');if(!known)s.cargoTypes.push({name:data.name.trim(),group:''});const l={id:'S'+n,name:known?.name||data.name.trim(),selected:true,quantity:data.quantity,cargoId:known?.id,sf:data.sf,sfBasis:known&&data.sf===known.sfDefault?known.sfBasis:'user-entered',propertySource:known?.propertyUrl||'',hazardClass:known?.hazardClass||'',loadPort:data.loadPort||'Ust-Luga',port:data.port,color:'hsl('+((n*137.508)%360).toFixed(2)+' 48% 64%)',onlyHold:known?.onlyHold,group:known?.group||'',un:known?.un||''};s.lots.push(l);return l;}
function ensureBusinessData(s){s.sales??=[];s.portRecords??=[];for(const l of s.lots){if(l.saleId)continue;let sale=s.sales.find(x=>x.legacyLotId===l.id);if(!sale){sale={id:'SALE-'+l.id,legacyLotId:l.id,dealDate:'',cargoId:l.cargoId||'',cargoName:l.name,quantity:l.quantity,loadPort:l.loadPort||'Ust-Luga',dischargePort:l.port,shipmentFrom:'',shipmentTo:'',fob:null};s.sales.push(sale);}l.saleId=sale.id;}for(const name of [...new Set(s.ports.map(p=>p.name))])if(!s.portRecords.some(p=>p.name===name))s.portRecords.push({id:'P'+(s.portRecords.length+1),name,terminal:'',restrictions:'',da:s.ports.find(p=>p.name===name)?.da??null});}
function syncSalesToLots(s){ensureBusinessData(s);for(const l of s.lots){const sale=s.sales.find(x=>x.id===l.saleId);if(sale){l.quantity=sale.quantity;l.loadPort=sale.loadPort;l.port=sale.dischargePort;}}syncRoute(s);}
function addSale(s,data){ensureCatalogs(s);ensureBusinessData(s);const cargo=s.cargoTypes.find(c=>c.id===data.cargoId);if(!cargo)throw Error('Выберите груз из CARGO');if(!ok(data.quantity,true))throw Error('Укажите положительный объём продажи');if(!ok(data.fob))throw Error('Укажите неотрицательную цену FOB');if(!data.dealDate||!data.shipmentFrom||!data.shipmentTo)throw Error('Укажите даты сделки и отгрузки');if(data.shipmentFrom>data.shipmentTo)throw Error('Начало отгрузки не может быть позже окончания');if(!data.loadPort?.trim()||!data.dischargePort?.trim())throw Error('Укажите порты погрузки и выгрузки');let n=1;while(s.sales.some(x=>x.id==='SALE-'+n))n++;const sale={id:'SALE-'+n,dealDate:data.dealDate,cargoId:cargo.id,cargoName:cargo.name,quantity:data.quantity,loadPort:data.loadPort.trim(),dischargePort:data.dischargePort.trim(),shipmentFrom:data.shipmentFrom,shipmentTo:data.shipmentTo,fob:data.fob};s.sales.push(sale);return sale;}
function addSaleToPlanner(s,saleId){ensureCatalogs(s);const sale=s.sales.find(x=>x.id===saleId);if(!sale)throw Error('Продажа не найдена');if(s.lots.some(l=>l.saleId===saleId))throw Error('Продажа уже добавлена в PLANNER');const cargo=s.cargoTypes.find(c=>c.id===sale.cargoId);if(!cargo||!isBulkCargo(cargo))throw Error('Этот груз недоступен для навалочного планирования');const ids=new Set(s.lots.map(l=>l.id));let n=1;while(ids.has('S'+n))n++;const l={id:'S'+n,saleId:sale.id,name:cargo.name,selected:true,quantity:sale.quantity,cargoId:cargo.id,sf:cargo.sf,sfBasis:cargo.sf===cargo.sfDefault?cargo.sfBasis:'catalog',propertySource:cargo.propertyUrl||'',hazardClass:cargo.hazardClass||'',loadPort:sale.loadPort,port:sale.dischargePort,color:'hsl('+((n*137.508)%360).toFixed(2)+' 48% 64%)',onlyHold:cargo.onlyHold,group:cargo.group||'',un:cargo.un||''};s.lots.push(l);syncRoute(s);return l;}
function syncRoute(s){const alias={"Ust'-Luga":'Ust-Luga','Saint Petersburg (ex Leningrad)':'St. Petersburg'};for(const l of s.lots)l.loadPort??=alias[s.ports[0]?.name]||s.ports[0]?.name||'Ust-Luga';const selected=active(s),loadNames=[...new Set(selected.map(l=>l.loadPort).filter(Boolean))],dischargeNames=[...new Set(selected.map(l=>l.port).filter(Boolean))],needed=new Set([...loadNames,...dischargeNames]),old=s.ports;s.portCache??={};for(const p of old)s.portCache[p.name]=JSON.parse(JSON.stringify(p));const ordered=[...old.map(p=>alias[p.name]||p.name).filter(n=>needed.has(n)),...loadNames.filter(n=>!old.some(p=>(alias[p.name]||p.name)===n)),...dischargeNames.filter(n=>!old.some(p=>(alias[p.name]||p.name)===n))];const unique=[...new Set(ordered)];unique.sort((a,b)=>(loadNames.includes(a)?0:1)-(loadNames.includes(b)?0:1));s.ports=unique.map(name=>{const found=old.find(p=>(alias[p.name]||p.name)===name)||s.portCache[name],record=s.portRecords?.find(p=>p.name===name);return found?{...found,name,da:found.da??record?.da??null}:{...port(name),da:record?.da??null,...(s.vesselSnapshot?{working:s.vesselSnapshot.working,idle:s.vesselSnapshot.idle,aux:s.vesselSnapshot.aux,auxWorking:s.vesselSnapshot.auxWorking,auxIdle:s.vesselSnapshot.auxIdle,boiler:s.vesselSnapshot.boiler,boilerDays:null,boilerFuel:null}:{})};});const calls=callsOf(s);if(calls.length&&s.ballast.to!==calls[0].name)s.ballast={...leg('Позиция судна',calls[0].name),...(s.vesselSnapshot?{speed:s.vesselSnapshot.ballastSpeed,burn:s.vesselSnapshot.ballastBurn,ecaBurn:s.vesselSnapshot.ecaBurn,aux:s.vesselSnapshot.aux}:{})};for(let i=1;i<calls.length;i++)if(!s.legs.some(l=>l.from===calls[i-1].name&&l.to===calls[i].name))s.legs.push({...leg(calls[i-1].name,calls[i].name),...(s.vesselSnapshot?{speed:s.vesselSnapshot.speed,burn:s.vesselSnapshot.burn,ecaBurn:s.vesselSnapshot.ecaBurn,aux:s.vesselSnapshot.aux}:{})});if(s.stage!=='load'&&!s.ports.some(p=>p.name===s.stage))s.stage='load';}
function moveCall(s,name,direction){if(![-1,1].includes(direction))return false;const loadNames=new Set(active(s).map(l=>l.loadPort)),isLoad=loadNames.has(name),group=callsOf(s).filter(p=>loadNames.has(p.name)===isLoad);const index=group.findIndex(p=>p.name===name),target=index+direction;if(index<0||target<0||target>=group.length)return false;const a=s.ports.indexOf(group[index]),b=s.ports.indexOf(group[target]);[s.ports[a],s.ports[b]]=[s.ports[b],s.ports[a]];syncRoute(s);s.stage='load';return true;}
function ensureCatalogs(s){s.cargoTypes??=JSON.parse(JSON.stringify(CARGO_TYPES));CargoCatalog.merge(s);s.cargoTypes.forEach((c,i)=>{c.id??='cargo-'+(i+1);c.sf??=null;c.source??='';});s.lots.forEach(l=>{const c=s.cargoTypes.find(c=>c.id===l.cargoId)||s.cargoTypes.find(c=>c.name===l.name);l.cargoId??=c?.id;l.group??=c?.group||'';l.un??=c?.un||'';});if(!s.vesselProfiles){s.vesselProfiles=JSON.parse(JSON.stringify(VESSELS));}ensureBusinessData(s);}
function applyCargo(s,id){ensureCatalogs(s);const c=s.cargoTypes.find(c=>c.id===id);if(c&&!isBulkCargo(c))throw Error('Этот продукт недоступен для навалочного расчёта');if(!c||!c.name.trim()||!ok(c.sf,true))throw Error('Укажите название и положительный SF');if(c.onlyHold!=null&&(!Number.isInteger(c.onlyHold)||c.onlyHold<1||c.onlyHold>s.holds.length))throw Error('Проверьте номер разрешённого трюма');if(!['','A','B','C','A & B'].includes(c.group))throw Error('Проверьте группу груза');if(c.un==='1350'&&c.onlyHold!==4)throw Error('Для crushed UN 1350 в этом кейсе разрешён только №4');for(const l of s.lots.filter(l=>l.cargoId===id)){Object.assign(l,{name:c.name,sf:c.sf,sfBasis:c.sf===c.sfDefault?c.sfBasis:'user-entered',propertySource:c.propertyUrl||'',hazardClass:c.hazardClass||'',group:c.group,un:c.un||'',onlyHold:c.onlyHold||undefined});} }
function applyVessel(s,id){ensureCatalogs(s);const v=s.vesselProfiles.find(v=>v.id===id);if(!v||!v.name.trim())throw Error('Укажите название судна');for(const k of ['dwt','draft','tpc','loa','beam','grain','bale','speed','ballastSpeed'])if(!ok(v[k],true))throw Error('Проверьте параметр судна: '+k);for(const k of ['burn','ballastBurn','working','idle','aux','auxWorking','auxIdle','boiler'])if(!ok(v[k]))throw Error('Проверьте расход: '+k);if(v.ecaBurn!==null&&!ok(v.ecaBurn))throw Error('Проверьте расход ECA');if(v.holdData.some(h=>!ok(h.volume,true)||(h.massLimit!==null&&!ok(h.massLimit,true))))throw Error('Проверьте параметры трюмов');if(!v.holdData.length)throw Error('Добавьте трюмы');v.holds=v.holdData.length;s.vesselId=id;s.vesselSnapshot=JSON.parse(JSON.stringify(v));s.holds=JSON.parse(JSON.stringify(v.holdData));s.legs.forEach(l=>Object.assign(l,{speed:v.speed,burn:v.burn,ecaBurn:v.ecaBurn,aux:v.aux}));Object.assign(s.ballast,{speed:v.ballastSpeed,burn:v.ballastBurn,ecaBurn:v.ecaBurn,aux:v.aux});[...s.ports,...Object.values(s.portCache||{})].forEach(p=>Object.assign(p,{working:v.working,idle:v.idle,aux:v.aux,auxWorking:v.auxWorking,auxIdle:v.auxIdle,boiler:v.boiler,boilerDays:p.boilerDays??null,boilerFuel:p.boilerFuel??null}));}
function migrateBaltic(s){ensureCatalogs(s);if(s.tbnSourceRevision===VESSELS[0].revision)return false;s.previousVesselProfile={profile:s.vesselProfiles.find(v=>v.id==='tbn-1'),snapshot:s.vesselSnapshot,holds:JSON.parse(JSON.stringify(s.holds)),constant:s.deductions.constant};const i=s.vesselProfiles.findIndex(v=>v.id==='tbn-1');const v=JSON.parse(JSON.stringify(VESSELS[0]));if(i<0)s.vesselProfiles.push(v);else s.vesselProfiles[i]=v;applyVessel(s,'tbn-1');s.deductions.constant=250;s.tbnSourceRevision=v.revision;return true;}
function anonymizeProfiles(s){const clean=v=>{if(!v)return;if(v.id==='tbn-1'&&v.revision!=='standard-tbn1-v1'){v.model='Стандартный балкер';v.source='Стандартный профиль TBN 1';v.revision='standard-tbn1-v1';}delete v.imo;delete v.imo_number;delete v.vessel_name;};s.vesselProfiles?.forEach(clean);clean(s.vesselSnapshot);if(s.previousVesselProfile){clean(s.previousVesselProfile.profile);clean(s.previousVesselProfile.snapshot);} }
function addVesselType(s){ensureCatalogs(s);let n=1;while(s.vesselProfiles.some(v=>v.id==='type-'+n))n++;const base=s.vesselProfiles.find(v=>v.id===s.vesselId)||s.vesselProfiles[0];const v=JSON.parse(JSON.stringify(base));v.id='type-'+n;v.name='Новый тип '+n;v.source='Копия параметров '+base.name;v.model='Стандартный балкер';v.revision='custom';s.vesselProfiles.push(v);return v;}
const api={isBulkCargo,anonymizeProfiles,addVesselType,migrateBaltic,ensureCatalogs,ensureBusinessData,syncSalesToLots,addSale,addSaleToPlanner,applyCargo,applyVessel,VESSELS,vesselOf,moveCall,LOAD_PORTS,loadOf,callsOf,syncRoute,CARGO_TYPES,changeLoadPort,addLot,initial,demo,allocate,stowage,compute,stageAllocations,splitCents,ok};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.ProjectXModel=api;
})(globalThis);
