'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),M=require('./model'),P=require('./planning');
const {Rational:R}=require('./arithmetic');
const base=()=>{const s=M.demo();P.ensure(s);return s;};
const nearly=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
test('Physical sums preserve decimal SF and reconcile declared grain without rewriting inputs',()=>{const s=base();s.lots[0].quantity=30000;s.lots[0].sf=.955;s.lots[1].selected=false;assert.equal(M.cargoVolume(s).volume,28650);const initial=M.initial();assert.equal(P.grain(initial).total,45516.8);assert.equal(P.grain(initial).difference,-.2);assert.equal(M.vesselOf(initial).grain,45517);});
test('Arrival and departure have different cargo balances; unassigned remains a loading-plan residual',()=>{const s=base(),events=P.events(s),arrival=events.find(e=>e.call.name==='Santos'&&e.phase==='arrival'),departure=events.find(e=>e.call.name==='Santos'&&e.phase==='departure');assert.equal(P.stageSummary(s,arrival.key).quantity,30000);assert.equal(P.stageSummary(s,departure.key).quantity,6000);assert.equal(P.stageSummary(s,departure.key).rows[0].unassigned,0);assert.equal(P.stageSummary(s,departure.key).rows[0].onBoard,0);assert.ok(P.stageSummary(s,departure.key).allocations.every(a=>a.lot==='S2'));s.stage=arrival.key;M.syncRoute(s);assert.equal(s.stage,arrival.key);});
test('Early loading stage excludes cargo not yet loaded',()=>{const s=base();s.lots[1].loadPort='Murmansk';M.syncRoute(s);P.ensure(s);const e=P.events(s).find(e=>e.call.name==='Murmansk'&&e.phase==='arrival');assert.equal(P.stageSummary(s,e.key).quantity,24000);});
test('New solver handles the order-dependent counterexample and preserves exact tonnes',()=>{for(const reverse of [false,true]){const s=base();s.holds=[{id:1,volume:10,massLimit:null},{id:2,volume:20,massLimit:null}];s.lots.forEach((l,i)=>Object.assign(l,{quantity:i?10:20,sf:1}));if(reverse)s.lots.reverse();const result=P.solve(s);assert.equal(result.status,'feasible');assert.equal(result.allocations.find(a=>a.lot==='S1').hold,2);assert.equal(result.allocations.find(a=>a.lot==='S2').hold,1);}});
test('Independent exhaustive ownership oracle agrees on 128 small packing problems',()=>{let seed=83;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed%12+1;};for(let k=0;k<128;k++){const capacities=[rnd(),rnd(),rnd()],quantities=[rnd(),rnd()];let feasible=false;for(let mask=0;mask<27;mask++){let m=mask,sums=[0,0];for(let h=0;h<3;h++){const owner=m%3;m=Math.floor(m/3);if(owner<2)sums[owner]+=capacities[h];}if(sums.every((q,i)=>q>=quantities[i]))feasible=true;}const s=base();s.holds=capacities.map((volume,i)=>({id:i+1,volume,massLimit:null}));s.lots.forEach((l,i)=>Object.assign(l,{quantity:quantities[i],sf:1}));const out=P.solve(s);assert.equal(out.status==='feasible',feasible,JSON.stringify({capacities,quantities,out}));if(feasible){const check=M.stowage({...s,allocations:out.allocations});assert.deepEqual(check.errors,[]);check.remaining.forEach(r=>nearly(r.quantity,0));}}});
test('Solver keeps one parcel distributed over all holds, uses bounded decimal quantities',()=>{const s=base();s.lots[1].selected=false;s.lots[0].quantity=10000.0001;const result=P.solve(s);assert.equal(result.status,'feasible');assert.equal(result.allocations.length,5);const q=result.allocations.reduce((sum,a)=>sum.add(a.quantity),R.from(0));assert.equal(q.sub(s.lots[0].quantity).n,0n);result.allocations.forEach(a=>assert.ok(String(a.quantity).length<15));});
test('Infeasible and interrupted searches never replace a manual plan',()=>{const s=base(),old=JSON.stringify(s.allocations);s.holds.forEach(h=>h.volume=1);assert.equal(P.solve(s).status,'no-solution-in-search-model');assert.throws(()=>P.applyPlan(s,P.solve(s)));assert.equal(JSON.stringify(s.allocations),old);const other=base();assert.equal(P.solve(other,0).status,'search-limit');});
test('Apply and undo preserve the exact manual allocation and survive serialization',()=>{let s=base();const old=JSON.stringify(s.allocations);P.applyPlan(s,P.solve(s));s=JSON.parse(JSON.stringify(s));P.undo(s);assert.equal(JSON.stringify(s.allocations),old);P.applyPlan(s,P.solve(s));s.holds[0].volume++;assert.throws(()=>P.undo(s),/changed/);});
test('Known limits and separation requirements are validated independently from solver output',()=>{const s=base();s.planning.limits=[{stage:'load',holds:[1,2],max:100,source:'Manual'}];assert.ok(P.check(s).errors.some(x=>x.includes('mass limit')));s.planning.compatibility=[{a:'S1',b:'S2',rule:'non-adjacent',source:'Declared separation'}];s.allocations=[{lot:'S1',hold:1,quantity:100},{lot:'S2',hold:2,quantity:100}];assert.ok(P.check(s).errors.some(x=>x.includes('separation')));});
test('Departure passes while arrival has the documented 400 tonne excess',()=>{const s=base(),e=P.events(s),load=e.find(x=>x.phase==='departure'&&x.call.name==='Ust-Luga'),arrival=e.find(x=>x.phase==='arrival'&&x.call.name==='Santos');load.call.planning.departure={allowableDwt:32500,fuel:1000,water:200,ballast:300,constant:500};arrival.call.planning.arrival={allowableDwt:31200,fuel:600,water:200,ballast:300,constant:500};assert.equal(P.stateCheck(s,load).margin,500);assert.equal(P.stateCheck(s,arrival).margin,-400);assert.ok(P.stateCheck(s,arrival).issues.some(x=>x.includes('400.000')));});
test('Unknown non-cargo masses do not become zero and displacement does not subtract draft loss twice',()=>{const s=base(),e=P.events(s)[0];e.call.planning.arrival={allowableDwt:32000,fuel:0,water:0,constant:0};assert.equal(P.stateCheck(s,e).limit,null);s.planning.vesselBasis={lightship:5000,vesselKey:JSON.stringify(M.vesselOf(s)),kind:'nominated'};s.deductions.draftLoss=1200;e.call.planning.arrival={mode:'displacement',displacement:37000,fuel:1000,water:200,ballast:300,constant:500};assert.equal(P.stateCheck(s,e).limit,30000);});
test('Berth screening uses state draft rather than reference profile draft',()=>{const s=base(),e=P.events(s).find(e=>e.call.name==='Santos'),berth=s.portRecords.find(p=>p.name==='Santos');berth.maxDraft=8;e.call.planning.berthId=berth.id;e.call.planning.arrival={draft:7};assert.ok(!P.stateCheck(s,e).issues.some(x=>x.includes('State draft')));e.call.planning.arrival.draft=9;assert.ok(P.stateCheck(s,e).issues.some(x=>x.includes('State draft')));});
test('Unit normalization distinguishes three kinds of ton and density basis',()=>{assert.equal(P.sfValue(800,'kg/m3'),1.25);assert.equal(P.sfValue(1,'ft3/metric-ton'),.028316846592);nearly(P.sfValue(1,'ft3/long-ton'),.027869625);assert.ok(P.sfValue(1,'ft3/short-ton')>P.sfValue(1,'ft3/metric-ton'));assert.throws(()=>P.sfValue(1,'ft3/ton'));});
const passport=()=>({value:.955,unit:'m3/t',basis:'declared',source:'Declaration 1',date:'2026-09-08',bcsn:'Declared material',group:'C',minSf:.9,maxSf:1});
test('Shipment properties retain versions and are not changed by catalogue edits',()=>{const s=base(),old=s.lots[0].sf;P.updatePassport(s,'S1',passport());s.cargoTypes[0].sf=1.2;M.ensureCatalogs(s);M.applyCargo(s,s.cargoTypes[0].id);assert.equal(s.lots[0].sf,.955);assert.equal(s.lots[0].passport.history[0].value,old);assert.equal(s.lots[0].passport.version,2);assert.throws(()=>P.updatePassport(s,'S1',{...passport(),source:''}));});
test('Planned quantity needs explicit permission and survives SALE synchronization',()=>{const s=base();assert.throws(()=>P.updatePassport(s,'S1',{...passport(),plannedQuantity:10000}));P.updatePassport(s,'S1',{...passport(),plannedQuantity:10000,quantitySource:'Split allowed',splitAllowed:true,minQuantity:9000,maxQuantity:12000});M.syncSalesToLots(s);assert.equal(s.lots[0].quantity,10000);assert.equal(s.sales[0].quantity,24000);});
test('Technical review covers explicit states and invalidates on berth input changes',()=>{const s=base(),first=P.events(s)[0];P.addReport(s,{reference:'Report',reviewer:'Surveyor',date:'2026-09-08',result:'accepted',covered:[first.key]});assert.equal(P.reportStatus(s),'partial');P.addReport(s,{reference:'Report all',reviewer:'Surveyor',date:'2026-09-08',result:'accepted',covered:P.events(s).map(e=>e.key)});assert.equal(P.reportStatus(s),'accepted');const c=s.ports[0];c.planning.berthId=s.portRecords.find(p=>p.name===c.name).id;assert.equal(P.reportStatus(s),'outdated');});
test('A saved snapshot remains reproducible after inputs change and after reload',()=>{const s=base(),x=P.freeze(s),original=JSON.stringify(x.input);s.lots[0].quantity=1;s.holds[0].volume=2;P.ensure(s);assert.equal(JSON.stringify(s.planning.snapshots[0].input),original);assert.equal(JSON.stringify(JSON.parse(JSON.stringify(s)).planning.snapshots[0].input),original);});
test('Invalid chronological events and shipment window differences are explicit',()=>{const s=base(),c=s.ports[0];c.planning.arrival.plannedAt='2026-09-10T10:00+03:00';c.planning.departure.plannedAt='2026-09-09T10:00+03:00';assert.ok(P.check(s).errors.some(x=>x.includes('previous event')));});

function draftFixture(){const s=base(),v=M.vesselOf(s);Object.assign(v,{dwt:30000,draft:10,tpc:50});s.planning.vesselBasis={kind:'reference',vesselKey:JSON.stringify(v),density:1.025,lightship:5000,source:'Particulars',date:'2026-09-08',dwtBasis:'Summer',tpcRangeCm:100,tpcSource:'Hydrostatic range'};Object.assign(s.deductions,{fuel:500,water:100,ballast:0,constant:400});for(const c of s.ports){const b=s.portRecords.find(p=>p.name===c.name);Object.assign(b,{maxDraft:9.8,waterDensity:1.025});c.planning.berthId=b.id;for(const phase of ['arrival','departure'])Object.assign(c.planning[phase],{fuel:500,water:100,ballast:0,constant:400,source:'Stores',date:'2026-09-08'});}return s;}
test('Draft estimate reconciles TPC and density without a fresh-water cargo bonus',()=>{const s=draftFixture();nearly(P.draftEstimate(s).loss,1000);for(const b of s.portRecords)b.waterDensity=1;const r=P.draftEstimate(s);nearly(r.limiting.allowedDwt,34000/1.025-5000);assert.ok(r.loss>1000);for(const b of s.portRecords){b.waterDensity=1.025;b.maxDraft=10.5;}nearly(P.draftEstimate(s).loss,0);});
test('Draft estimate uses state stores and requires range and all full-load states',()=>{const s=draftFixture(),c=s.ports.find(c=>c.name==='Santos');c.planning.arrival.fuel=200;nearly(P.draftEstimate(s).loss,1000);s.ports[0].planning.departure.fuel=100;nearly(P.draftEstimate(s).loss,700);s.planning.vesselBasis.tpcRangeCm=10;assert.equal(P.draftEstimate(s).loss,null);assert.throws(()=>P.applyDraftEstimate(s,P.inputKey(s)));s.planning.vesselBasis.tpcRangeCm=100;delete c.planning.arrival.water;assert.equal(P.draftEstimate(s).loss,null);});
test('Density selection validates, clears and invalidates a draft preview',()=>{const s=draftFixture(),key=P.inputKey(s),idx=s.portRecords.findIndex(p=>p.id===s.ports[0].planning.berthId);M.updatePortRecord(s,idx,'waterDensity','1.02');assert.equal(s.portRecords[idx].waterDensity,1.02);assert.throws(()=>P.applyDraftEstimate(s,key));assert.throws(()=>M.updatePortRecord(s,idx,'waterDensity','1020'));M.updatePortRecord(s,idx,'waterDensity','');assert.equal(s.portRecords[idx].waterDensity,null);assert.equal(P.draftEstimate(s).complete,false);});
test('Applying a draft estimate preserves evidence and never deducts old draft loss twice',()=>{const s=draftFixture();s.deductions.draftLoss=999;const r=P.applyDraftEstimate(s,P.inputKey(s));nearly(s.deductions.draftLoss,1000);assert.equal(s.planning.draftEstimate.rows.length,P.events(s).length);nearly(P.draftEstimate(s).loss,r.loss);assert.ok(!P.check(s).warnings.some(x=>x.includes('draft loss estimate is outdated')));s.portRecords.find(p=>p.id===s.ports[0].planning.berthId).waterDensity=1.02;assert.ok(P.check(s).warnings.some(x=>x.includes('draft loss estimate is outdated')));});

test('Automatic draft loss requires no source forms and follows vessel and route limits',()=>{const s=base();for(const b of s.portRecords){b.maxDraft=20;b.waterDensity=1.025;}const first=s.portRecords.find(p=>p.name===s.ports[0].name);first.maxDraft=M.vesselOf(s).draft-.3;nearly(P.syncAutoDraftLoss(s).loss,M.vesselOf(s).tpc*30);assert.equal(s.planning.vesselBasis,undefined);first.maxDraft=20;nearly(P.syncAutoDraftLoss(s).loss,0);first.maxDraft=null;assert.equal(P.syncAutoDraftLoss(s).loss,null);});
test('Automatic density correction never invents lightship or changes the selected berth',()=>{const s=base();for(const b of s.portRecords){b.maxDraft=M.vesselOf(s).draft;b.waterDensity=1;}let r=P.autoDraftLoss(s);assert.ok(r.warnings.some(x=>x.includes('needs lightship')));assert.ok(!r.rows.some(x=>x.densityApplied));assert.equal(r.loss,0);const v=M.vesselOf(s);s.planning.vesselBasis={lightship:5000,density:1.025,vesselKey:JSON.stringify(v)};r=P.autoDraftLoss(s);assert.ok(r.loss>0);assert.ok(s.ports.every(c=>!c.planning.berthId));});

test('A voyage with no draft restriction says so and names the shallowest limit',()=>{
 const s=M.demo();M.applyVessel(s,'tbn-1');P.ensure(s);
 const r=P.autoDraftLoss(s);
 assert.equal(r.loss,0,'a 9.85 m draft clears every limit on this rotation');
 assert.match(r.reason,/^No draft restriction/,'zero reads as an answer, not a failure');
 assert.equal(r.limiting.call,'Santos','the tightest call is named, not the first');
 assert.ok(r.rows.every(x=>x.maxDraft>=r.limiting.maxDraft),'no call has a shallower limit');
 const deep=M.demo();M.applyVessel(deep,'tbn-3');P.ensure(deep);
 const restricted=P.autoDraftLoss(deep);
 assert.ok(restricted.loss>0);
 assert.match(restricted.reason,/^TPC estimate · Santos/,'a real restriction still names its call');
});

test('The density note names the actual obstacle, not a generic one',()=>{
 const basis=s=>({vesselKey:JSON.stringify(M.vesselOf(s)),kind:'reference',source:'P',date:'2026-09-08',dwtBasis:'Summer SW',density:1.025,lightship:10800,tpcRangeCm:200,tpcSource:'Hydro'});
 const fresh=M.demo();M.applyVessel(fresh,'tbn-3');P.ensure(fresh);
 assert.match(P.autoDraftLoss(fresh).densityNote,/enter lightship in Vessel source/,'nothing recorded yet');
 const stale=M.demo();M.applyVessel(stale,'tbn-1');P.ensure(stale);stale.planning.vesselBasis=basis(stale);
 M.applyVessel(stale,'tbn-3');
 const note=P.autoDraftLoss(stale).densityNote;
 assert.match(note,/recorded for another vessel/,'lightship was entered, so asking for it again would be wrong');
 assert.doesNotMatch(note,/enter lightship/,'the stale basis must not read as a missing lightship');
 const ready=M.demo();M.applyVessel(ready,'tbn-3');P.ensure(ready);ready.planning.vesselBasis=basis(ready);
 const r=P.autoDraftLoss(ready);
 assert.equal(r.densityNote,null,'a complete basis leaves no note');
 assert.ok(r.rows.every(x=>x.densityApplied),'and every call is density corrected');
});

