(function(root){
'use strict';
// toLocaleString builds a fresh Intl.NumberFormat on every call and is the hottest thing in a render.
// One formatter per digit count produces the same string.
const numberFormats=new Map();
const numberFormat=digits=>{let f=numberFormats.get(digits);if(!f){f=new Intl.NumberFormat('en-GB',{minimumFractionDigits:digits,maximumFractionDigits:digits});numberFormats.set(digits,f);}return f;};
function create(env){
 const {M,P,getState,changed}=env,$=id=>document.getElementById(id);
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const n=x=>Number.isFinite(x)?String(x):'—',fmt=(x,d=2)=>Number.isFinite(x)?numberFormat(d).format(x):'—';
 const btn=(action,label,attrs='')=>`<button type="button" data-action="${action}" ${attrs}>${label}</button>`;
 const table=(head,rows)=>`<div class="table-wrap"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
 function state(){return getState();}
 function grainNote(s){const g=P.grain(s);return g.difference!==null&&Math.abs(g.difference)>1e-7?`<button type="button" class="inline-action" data-action="vessel-basis">Declared ${fmt(g.declared)} m³ · difference ${fmt(g.difference)} m³</button>`:'';}
 function motionSnapshot(){const map=new Map();if(typeof document==='undefined'||typeof document.querySelectorAll!=='function'||typeof getComputedStyle!=='function')return map;document.querySelectorAll('.cargo-fill').forEach(el=>map.set(el.dataset.fillKey,getComputedStyle(el).transform));return map;}
 function animate(map){if(!map.size||typeof matchMedia!=='function'||matchMedia('(prefers-reduced-motion: reduce)').matches||matchMedia('print').matches)return;document.querySelectorAll('.cargo-fill').forEach(el=>{const target=el.style.transform,from=map.get(el.dataset.fillKey)||'translate(0px, 215px) scale(1, 0)';if(el.animate&&from!==getComputedStyle(el).transform)el.animate([{transform:from},{transform:target}],{duration:280,easing:'cubic-bezier(0.23, 1, 0.32, 1)'});});}
 function draw(s){
  const summary=P.stageSummary(s),lots=s.lots.filter(l=>l.selected);let blocks='';
  for(let i=0;i<s.holds.length;i++){
   const w=815/s.holds.length-17,h=summary.holds[s.holds.length-1-i],x=180+i*(w+17);let bottom=215,bars='';
   for(const l of lots){const cells=h.cells.filter(a=>a.lot===l.id),q=cells.every(a=>M.ok(a.quantity))?P.exactSum(cells.map(a=>a.quantity)):0,volume=M.ok(l.sf,true)?q*l.sf:0,height=M.ok(h.volume,true)?Math.max(0,Math.min(bottom-85,volume/h.volume*130)):0;
    bars+=`<rect class="cargo-fill" data-fill-key="${esc(h.id+'|'+l.id)}" x="${x+1}" y="0" width="${w-2}" height="1" fill="${esc(l.color)}" opacity=".7" style="transform:translate(0px, ${bottom-height}px) scale(1, ${height});transform-origin:0 0"/>`;bottom-=height;
   }
   const contents=lots.filter(l=>h.cells.some(a=>a.lot===l.id&&a.quantity>0));
   blocks+=`<g class="hold ${h.fill>100?'hold-exceeded':''}" aria-label="Hold ${h.id}: ${esc(contents.map(l=>l.name).join(', ')||'Empty')}; ${fmt(h.mass)} t; ${fmt(h.fill,1)} percent"><title>${esc(contents.map(l=>l.name).join(' / ')||'Empty hold')}</title><rect class="hold-outline" x="${x}" y="85" width="${w}" height="130" rx="3"/>${bars}<text x="${x+w/2}" y="65" text-anchor="middle" font-size="13">№${h.id}</text><foreignObject x="${x+7}" y="94" width="${w-14}" height="112"><div xmlns="http://www.w3.org/1999/xhtml" class="hold-names">${contents.map(l=>`<div>${esc(l.name)}</div>`).join('')||'<span class="muted">Empty</span>'}<div class="hold-stat">${fmt(h.fill,1)}% · ${fmt(h.mass,1)} t</div></div></foreignObject><text x="${x+w/2}" y="260" text-anchor="middle" font-size="11">${fmt(h.volume)} m³</text></g>`;
  }
  return `<svg class="ship" viewBox="0 0 1120 300" role="group" aria-label="Stowage: aft left, forward right"><path d="M25 74 Q25 45 55 45 H998 Q1058 58 1090 160 Q1058 262 998 275 H55 Q25 275 25 245 Z" fill="none" stroke="#606060" stroke-width="1.5"/><text class="ship-end" x="88" y="165" font-size="10" text-anchor="middle">AFT</text>${blocks}<text class="ship-end" x="1058" y="165" font-size="10" text-anchor="middle">FWD</text></svg>`;
 }
 // Every arrival and departure draft follows from that state's own displacement.
 const stateLabel=r=>(r.phase==='arrival'?'Arrival · ':'Departure · ')+r.call;
 function draftTable(s,rows){
 const cell=(r,k)=>r.computed?fmt(r.computed[k],2):'—';
 const body=rows.map(r=>{
   const label=stateLabel(r);
   return `<tr><td class="name">${esc(label)}</td><td>${fmt(r.cargo,0)}</td><td>${fmt(r.deadweight,0)}</td><td>${cell(r,'mid')}</td><td>${cell(r,'aft')}</td><td>${cell(r,'fwd')}</td><td>${r.deepest===null?'—':fmt(r.deepest,2)}${r.basis==='computed'?'':' <small>'+esc(r.basis)+'</small>'}</td></tr>`;});
  return table(['State','Cargo, t','Deadweight, t','Mean, m','Aft, m','Fwd, m','Deepest, m'],body)
   +'<p class="form-note">Mean draft is the load-line reference draft corrected by (reference DWT − state deadweight) / TPC and by the berth water density. Cargo comes from the stowage plan, bunkers from the voyage consumption chained to the intake figure; a value entered for the state overrides both. Aft and forward split the entered trim about amidships: the platform holds no MCTC or LCF, so they are not a trim calculation. A surveyed or entered state draft in Berth / states governs the berth check instead.</p>';
 }
 // Hidden by default; the summary keeps the binding state, and any breach, in view.
 function draftsBlock(s,budget,rows){
  rows=rows||P.stateDrafts(s,budget);
  if(!rows.length)return '<h3>Drafts</h3><p class="muted">Add sales to the voyage to calculate departure and arrival drafts.</p>';
  const measured=rows.filter(r=>r.deepest!==null);
  const over=rows.filter(r=>r.margin!==null&&r.margin<0);
  // A draft with no berth limit beside it is unverified, not clear: it must not read as an all-clear.
  const unchecked=rows.filter(r=>r.margin===null);
  const deepest=measured.length?measured.reduce((a,b)=>b.deepest>a.deepest?b:a):null;
  const tightest=rows.filter(r=>r.margin!==null).sort((a,b)=>a.margin-b.margin)[0]||null;
  const parts=[];
  if(over.length)parts.push(`<strong class="over-limit">${over.length} over the berth limit</strong>`);
  if(unchecked.length)parts.push(`${unchecked.length} not checked against a berth limit`);
  if(deepest)parts.push(`deepest <strong>${fmt(deepest.deepest,2)} m</strong> at ${esc(stateLabel(deepest))}`);
  if(tightest&&!over.length)parts.push(`tightest margin ${fmt(tightest.margin,2)} m at ${esc(stateLabel(tightest))}`);
  // Always collapsed on open: the summary carries the alarm, and the claim is repeated under the table.
  return `<details id="drafts" class="fold"><summary><strong>Drafts</strong><span>${parts.join(' · ')||'No draft calculated'}</span></summary><div class="fold-body">${draftTable(s,rows)}</div></details>`;
 }
 function section3(s,budget,report){const summary=P.stageSummary(s);report=report||P.check(s,budget);const editable=s.stage==='load';return `<section id="stowage-section"><div class="heading"><h2>3. Stowage by hold</h2><div class="button-row">${btn('allocate','Allocate by volume',!summary.rows.length?'disabled':'')}${s.planning?.undo?btn('undo-plan','Undo'):''}${btn('planning-checks','Checks')}</div></div><div class="route"><select data-path="stage" aria-label="Cargo plan stage"><option value="load" ${editable?'selected':''}>After all loadings · edit plan</option>${P.events(s).map(e=>`<option value="${esc(e.key)}" ${P.resolveStage(s)?.key===e.key?'selected':''}>${esc(e.label)}</option>`).join('')}</select><span data-stage-total>${fmt(summary.quantity,3)} t on board</span>${!editable?btn('edit-plan','Edit loading plan'):''}<span class="planning-status">${report.technical==='not-reviewed'?'Technical review pending':esc('Technical review: '+report.technical)}</span></div><div class="ship-wrap">${draw(s)}</div><div class="table-wrap"><table class="allocation"><thead><tr><th>Sale / cargo</th>${s.holds.map(h=>`<th>№${h.id}</th>`).join('')}<th>Unassigned, t</th><th>On board, t</th></tr></thead><tbody>${summary.rows.map(l=>`<tr><td class="name"><span class="tag" style="background:${esc(l.color)}"></span><small>${esc(l.saleId||l.id)}</small><br>${esc(l.name)}</td>${s.holds.map(h=>{const q=summary.allocations.filter(a=>a.lot===l.id&&a.hold===h.id).reduce((n,a)=>n+(a.quantity??0),0);return `<td>${editable?`<input type="number" min="0" step="any" data-lot="${esc(l.id)}" data-hold="${h.id}" aria-label="${esc(l.name)} hold ${h.id}" value="${q||''}" placeholder="—">`:fmt(q,3)}</td>`;}).join('')}<td data-unassigned="${esc(l.id)}">${fmt(l.unassigned,3)}</td><td>${fmt(l.onBoard,3)}</td></tr>`).join('')}</tbody></table></div>${draftsBlock(s,budget,report.drafts)}<div id="plan-errors">${report.errors.map(x=>`<p class="error">${esc(x)}</p>`).join('')}</div></section>`;}
 function refresh(){const s=state(),wrap=document.querySelector('#stowage-section .ship-wrap');if(!wrap)return;const before=motionSnapshot();wrap.innerHTML=draw(s);animate(before);const summary=P.stageSummary(s);document.querySelectorAll('[data-unassigned]').forEach(el=>el.textContent=fmt(summary.rows.find(l=>l.id===el.dataset.unassigned)?.unassigned,3));const errors=$('plan-errors');if(errors)errors.innerHTML=P.check(s).errors.map(x=>`<p class="error">${esc(x)}</p>`).join('');}
 function modal(title,body,onSave,label='Save'){const d=document.createElement('dialog');d.className='planning-dialog';d.innerHTML=`<form><div class="heading"><h2>${esc(title)}</h2><button type="button" data-close aria-label="Close">×</button></div>${body}<p class="error" role="alert"></p>${onSave?`<button type="submit" class="primary">${esc(label)}</button>`:''}</form>`;document.body.appendChild(d);d.querySelector('[data-close]').onclick=()=>{d.close();d.remove();};d.addEventListener('close',()=>d.remove());d.querySelector('form').onsubmit=e=>{e.preventDefault();if(!onSave)return;try{onSave(new FormData(e.target));d.close();d.remove();changed();}catch(error){d.querySelector('.error').textContent=error.message;}};d.showModal();return d;}
 const field=(key,label,value='',type='text',required=false)=>`<label class="field">${label}<input name="${key}" type="${type}" value="${esc(value??'')}" ${type==='number'?'step="any" min="0"':''} ${required?'required':''}></label>`;
 const select=(key,label,value,options)=>`<label class="field">${label}<select name="${key}">${options.map(o=>{const [v,t]=Array.isArray(o)?o:[o,o];return `<option value="${esc(v)}" ${v===value?'selected':''}>${esc(t)}</option>`;}).join('')}</select></label>`;
 const val=(f,k)=>String(f.get(k)||'').trim(),number=(f,k)=>val(f,k)===''?null:Number(f.get(k)), grid=x=>`<div class="grid">${x}</div>`;
 function passport(lotId,edit=false){const s=state(),l=s.lots.find(l=>l.id===lotId);if(!l)return;P.ensure(s);const p=l.passport,c=s.cargoTypes.find(c=>c.id===l.cargoId);
  if(!edit){const d=modal(l.name,`<dl class="evidence"><dt>Sale</dt><dd>${esc(l.saleId)}</dd><dt>Shipment SF</dt><dd>${n(l.sf)} m³/t · ${esc(p.basis)}</dd><dt>Source</dt><dd>${esc(p.source||'Not entered')} · ${esc(p.date||'No date')}</dd><dt>BCSN</dt><dd>${esc(p.bcsn||'Not declared')}</dd><dt>Current catalogue SF</dt><dd>${n(c?.sf)} m³/t ${c?.sf!==l.sf?`· volume difference ${fmt((c.sf-l.sf)*l.quantity)} m³`:''}</dd><dt>Volume</dt><dd>${n(l.quantity)} × ${n(l.sf)} = ${fmt(l.quantity*l.sf)} m³</dd><dt>Version</dt><dd>${p.version}</dd></dl>${btn('source-in-sale','Edit shipment source in SALE')}`);d.querySelector('[data-action="source-in-sale"]').onclick=()=>{d.close();d.remove();env.openTab('sale');passport(lotId,true);};return;}
  modal('Shipment properties · '+l.saleId,grid(field('value','Source SF / bulk density',p.value??l.sf,'number',true)+select('unit','Original unit',p.unit||'m3/t',[['m3/t','m³/t'],['ft3/metric-ton','ft³ / metric ton'],['ft3/long-ton','ft³ / long ton'],['ft3/short-ton','ft³ / short ton'],['kg/m3','Bulk density, kg/m³']])+select('basis','Basis',p.basis,[['reference','Reference'],['declared','Declared shipment'],['density-estimate','Estimated from density']])+field('source','Source document / reference',p.source)+field('date','Source date',p.date,'date')+field('bcsn','BCSN',p.bcsn)+field('specification','Specification / physical form',p.specification)+select('group','IMSBC group',l.group||'',['','A','B','C','A & B'])+field('hazardClass','Hazard class',p.hazardClass??l.hazardClass)+field('un','UN number',p.un??l.un)+field('minSf','Minimum SF, m³/t',p.minSf,'number')+field('maxSf','Maximum SF, m³/t',p.maxSf,'number')+field('codeVersion','IMSBC edition / amendment',p.codeVersion)+field('mc','Moisture certificate reference, if applicable',p.mc)+field('tml','TML certificate reference, if applicable',p.tml)+field('plannedQuantity','Planned quantity, t',l.quantity,'number',true)+field('minQuantity','Permitted minimum, t',p.minQuantity,'number')+field('maxQuantity','Permitted maximum, t',p.maxQuantity,'number')+select('splitAllowed','Quantity variation / split allowed',p.splitAllowed?'yes':'no',[['no','Not established'],['yes','Allowed by referenced source']])+field('quantitySource','Quantity permission source',p.quantitySource))+`<p class="muted">Updates this shipment snapshot. The previous version is retained.</p>`,f=>{P.updatePassport(s,lotId,{value:number(f,'value'),unit:val(f,'unit'),basis:val(f,'basis'),source:val(f,'source'),date:val(f,'date'),bcsn:val(f,'bcsn'),specification:val(f,'specification'),group:val(f,'group'),minSf:number(f,'minSf'),maxSf:number(f,'maxSf'),codeVersion:val(f,'codeVersion'),mc:val(f,'mc'),tml:val(f,'tml'),hazardClass:val(f,'hazardClass'),un:val(f,'un'),plannedQuantity:number(f,'plannedQuantity'),minQuantity:number(f,'minQuantity'),maxQuantity:number(f,'maxQuantity'),splitAllowed:val(f,'splitAllowed')==='yes',quantitySource:val(f,'quantitySource')});});
 }
 function vesselBasis(){const s=state();P.ensure(s);const b=s.planning.vesselBasis||{},g=P.grain(s);modal('Vessel source and capacity',`<p>Vessel basis: ${esc(P.vesselBasisStatus(s))}</p><p>Hold total ${fmt(g.total)} m³ · declared grain ${fmt(g.declared)} m³ · difference ${fmt(g.difference)} m³</p>`+grid(select('kind','Vessel basis',b.kind||'reference',[['reference','Reference type'],['nominated','Nominated vessel']])+field('imo','IMO',b.imo)+field('source','Particulars source',b.source||M.vesselOf(s)?.source)+field('date','Source date',b.date,'date')+field('dwtBasis','DWT / load-line basis',b.dwtBasis)+field('density','Reference water density, t/m³',b.density,'number')+field('lightship','Lightship, t',b.lightship,'number')+field('tpcRangeCm','TPC valid deviation from reference draft, cm',b.tpcRangeCm,'number')+field('tpcSource','TPC range / hydrostatic source',b.tpcSource)),f=>{const kind=val(f,'kind'),imo=val(f,'imo');if(kind==='nominated'&&(!/^\d{7}$/.test(imo)||!val(f,'source')||!val(f,'date')))throw Error('A nominated vessel needs IMO, particulars source and date');s.planning.vesselBasis={vesselKey:JSON.stringify(M.vesselOf(s)),kind,imo,source:val(f,'source'),date:val(f,'date'),dwtBasis:val(f,'dwtBasis'),density:number(f,'density'),lightship:number(f,'lightship'),tpcRangeCm:number(f,'tpcRangeCm'),tpcSource:val(f,'tpcSource')};});}
 function intakeBasis(){const s=state();P.ensure(s);const b=s.planning.intakeBasis;modal('Intake basis',grid(field('state','Deductions refer to',b.state)+field('source','Deductions source',b.source)+field('date','Source date',b.date,'date')+field('constantIncludes','Constant includes',b.constantIncludes)+field('draftLossSource','Draft loss calculation / source',b.draftLossSource)+field('draftLossCall','Limiting call / state',b.draftLossCall))+(b.legacyDraftLoss?'<p class="muted">Draft loss 0 was inherited from the previous calculation; its source is not confirmed.</p>':''),f=>{s.planning.intakeBasis=Object.fromEntries(['state','source','date','constantIncludes','draftLossSource','draftLossCall'].map(k=>[k,val(f,k)]));});}
 function callSource(callId){const s=state(),c=s.ports.find(c=>c.callId===callId);if(!c)return;const p=c.planning,berths=s.portRecords.filter(b=>b.name===c.name);let body=select('berthId','Terminal / berth',p.berthId,[['','Select a berth'],...berths.map(b=>[b.id,[b.terminal,b.berth].filter(Boolean).join(' · ')||b.name])]);body+='<div class="state-columns">';for(const phase of ['arrival','departure']){const d=p[phase]||{};body+=`<fieldset><legend>${phase==='arrival'?'Arrival':'Departure'}</legend>`+grid(select(phase+'.mode','Mass basis',d.mode||'dwt',[['dwt','Allowed deadweight'],['displacement','Allowed displacement less lightship']])+field(phase+'.allowableDwt','Allowed deadweight, t',d.allowableDwt,'number')+field(phase+'.displacement','Allowed displacement, t',d.displacement,'number')+['fuel','water','ballast','constant'].map(k=>field(phase+'.'+k,k[0].toUpperCase()+k.slice(1)+', t',d[k],'number')).join('')+field(phase+'.draft','Actual / planned draft, m',d.draft,'number')+field(phase+'.airDraft','State air draft, m',d.airDraft,'number')+field(phase+'.source','State / allowed mass source',d.source)+field(phase+'.date','Source date',d.date,'date')+field(phase+'.plannedAt','Event time · ISO with UTC offset',d.plannedAt))+'</fieldset>';}
 body+='</div><p class="muted">Allowed mass is entered from a state-specific source. Draft loss is not deducted again. Displacement mode requires lightship in Vessel source.</p>';
 modal(c.name+' · state checks',body,f=>{const next={berthId:val(f,'berthId')};for(const phase of ['arrival','departure']){next[phase]={mode:val(f,phase+'.mode'),source:val(f,phase+'.source'),date:val(f,phase+'.date'),plannedAt:val(f,phase+'.plannedAt')};for(const k of ['allowableDwt','displacement','fuel','water','ballast','constant','draft','airDraft']){const x=number(f,phase+'.'+k);if(x!==null&&!M.ok(x))throw Error('Enter non-negative state values');next[phase][k]=x;}}c.planning=next;});
 }
 function preview(){const s=state(),r=P.solve(s);if(r.status!=='feasible'){modal('Automatic plan',`<p>${r.status==='search-limit'?'Search limit reached. No complete plan found yet.':'No complete plan found under the separate-hold search model.'}</p><p class="muted">${esc(r.scope||'Complete cargo SF, quantities and hold volumes.')} Existing allocations are unchanged.</p>`);return;}
 const rows=s.lots.filter(l=>l.selected).map(l=>`<tr><td>${esc(l.name)}</td>${s.holds.map(h=>{const old=s.allocations.filter(a=>a.lot===l.id&&a.hold===h.id).reduce((n,a)=>n+a.quantity,0),q=r.allocations.filter(a=>a.lot===l.id&&a.hold===h.id).reduce((n,a)=>n+a.quantity,0);return `<td>${fmt(old,3)} → ${fmt(q,3)}</td>`;}).join('')}</tr>`),key=P.inputKey(s);
 modal('Preview complete allocation',table(['Cargo',...s.holds.map(h=>'№'+h.id+' · t')],rows)+'<p class="muted">Volume and entered mass/separation constraints. Technical review remains separate.</p>',()=>{if(P.inputKey(s)!==key)throw Error('Inputs changed; prepare a new preview');P.applyPlan(s,r);},'Apply plan');}
 function compatibility(){const s=state(),lots=s.lots.filter(l=>l.selected);let pairs=[];for(let i=0;i<lots.length;i++)for(let j=i+1;j<lots.length;j++)pairs.push([lots[i],lots[j]]);modal('Cargo compatibility',pairs.map(([a,b],i)=>{const r=s.planning.compatibility.find(r=>[r.a,r.b].includes(a.id)&&[r.a,r.b].includes(b.id))||{};return `<fieldset><legend>${esc(a.name)} / ${esc(b.name)}</legend>`+grid(select('rule'+i,'Relationship',r.rule||'unknown',[['unknown','Not established'],['same-hold','Same hold permitted'],['separate-holds','Separate holds required'],['non-adjacent','Non-adjacent holds required']])+field('source'+i,'Source / conditions',r.source))+'</fieldset>';}).join('')||'<p>Add two selected parcels to define a relationship.</p>',f=>{s.planning.compatibility=pairs.map(([a,b],i)=>{const rule=val(f,'rule'+i),source=val(f,'source'+i);if(rule!=='unknown'&&!source)throw Error('Every established relationship needs a source');return {a:a.id,b:b.id,rule,source};});});}
 function technicalReport(){const s=state();modal('Record external technical review',grid(field('reference','Report document / reference','','text',true)+field('reviewer','Reviewer','','text',true)+field('date','Review date','','date',true)+select('result','Result','conditional',[['conditional','Conditional'],['accepted','Accepted'],['rejected','Rejected']])+field('conditions','Conditions'))+`<fieldset><legend>States covered by this report</legend>${P.events(s).map(e=>`<label class="check-line"><input type="checkbox" name="covered" value="${esc(e.key)}"> ${esc(e.label)}</label>`).join('')}</fieldset>`,f=>P.addReport(s,{reference:val(f,'reference'),reviewer:val(f,'reviewer'),date:val(f,'date'),result:val(f,'result'),conditions:val(f,'conditions'),covered:f.getAll('covered')}),'Record review');}
 function checks(){const s=state(),r=P.check(s),d=modal('Planner checks',`<p>Loading plan: ${esc(r.status)} · technical review: ${esc(r.technical)}</p>${r.errors.map(x=>`<p class="error">${esc(x)}</p>`).join('')}${r.warnings.map(x=>`<p class="muted">${esc(x)}</p>`).join('')}`+table(['State','On board, t','Cargo limit, t','Margin, t','Check'],r.states.map(st=>`<tr><td>${esc(st.label)}</td><td>${fmt(st.quantity,3)}</td><td>${fmt(st.limit,3)}</td><td>${fmt(st.margin,3)}</td><td class="state-check-text">${esc([...st.issues,...st.missing].join('; ')||st.status)}</td></tr>`))+`<div class="button-row">${btn('vessel-basis','Vessel source')}${btn('intake-basis','Intake basis')}${btn('compatibility','Cargo compatibility')}${btn('technical-report','Record technical review')}${btn('freeze-plan','Save plan version')}</div>`+`<h3>Saved plan versions</h3>${(s.planning.snapshots||[]).map((x,i)=>btn('view-snapshot',esc(x.createdAt),`data-index="${i}"`)).join('')||'<p class="muted">None saved yet.</p>'}`);
 d.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;d.close();d.remove();action(b.dataset.action,b);});}
 function printEvidence(s,budget,report){const r=report||P.check(s,budget);return `<div class="print-evidence"><h3>Planner evidence</h3><p>Vessel basis: ${esc(P.vesselBasisStatus(s))} · ${esc(s.planning?.vesselBasis?.source||M.vesselOf(s)?.source||'No source')} · ${esc(s.planning?.vesselBasis?.date||'No date')}</p><p>Intake state: ${esc(s.planning?.intakeBasis?.state)} · source ${esc(s.planning?.intakeBasis?.source||'Not entered')} · draft loss ${esc(s.planning?.intakeBasis?.draftLossSource||'Not sourced')}</p>${table(['Sale','Shipment basis','SF, m³/t','Source / date'],s.lots.filter(l=>l.selected).map(l=>`<tr><td>${esc(l.saleId)} · ${esc(l.name)}</td><td>${esc(l.passport?.basis)}</td><td>${n(l.sf)}</td><td>${esc(l.passport?.source||'Not entered')} · ${esc(l.passport?.date||'No date')}</td></tr>`))}${table(['State','Cargo, t','Limit, t','Deadweight, t','Draft, m','Draft basis','Check'],r.states.map(st=>`<tr><td>${esc(st.label)}</td><td>${fmt(st.quantity,3)}</td><td>${fmt(st.limit,3)}</td><td>${fmt(st.draft?.deadweight,1)}</td><td>${fmt(st.draft?.deepest,2)}</td><td>${esc(st.draft?.basis||'unavailable')}</td><td>${esc([...st.issues,...st.missing].join('; ')||st.status)}</td></tr>`))}<p>Technical review: ${esc(r.technical)}. Volume allocation is not a stability or strength calculation.</p></div>`;}
 function action(name,el){P.ensure(state());switch(name){case'allocate':preview();return true;case'undo-plan':try{P.undo(state());changed();}catch(e){modal('Previous plan',`<p>${esc(e.message)}</p>`);}return true;case'edit-plan':state().stage='load';changed();return true;case'parcel-passport':passport(el.dataset.id);return true;case'edit-passport':passport(el.dataset.id,true);return true;case'vessel-basis':vesselBasis();return true;case'intake-basis':intakeBasis();return true;case'call-source':callSource(el.dataset.id);return true;case'planning-checks':checks();return true;case'compatibility':compatibility();return true;case'technical-report':technicalReport();return true;case'freeze-plan':P.freeze(state());changed();checks();return true;case'view-snapshot':{const x=state().planning.snapshots[Number(el.dataset.index)];modal('Saved plan · '+x.createdAt,`<p>Read-only snapshot · ${esc(x.check.status)}</p>${table(['Sale','Cargo','Quantity, t','SF, m³/t','Source'],x.input.lots.map(l=>`<tr><td>${esc(l.saleId)}</td><td>${esc(l.name)}</td><td>${fmt(l.quantity,3)}</td><td>${n(l.sf)}</td><td>${esc(l.passport?.source||'Not entered')}</td></tr>`))}${table(['Hold','Cargo','Allocated, t'],x.input.allocations.map(a=>`<tr><td>№${a.hold}</td><td>${esc(x.input.lots.find(l=>l.id===a.lot)?.name)}</td><td>${fmt(a.quantity,3)}</td></tr>`))}`);return true;}default:return false;}}
 return {draw,section3,printEvidence,grainNote,motionSnapshot,animate,refresh,action};
}
const api={create};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.ProjectXPlannerUI=api;
})(globalThis);
